### ISSUE TITLE
Missing RFC

### ISSUE THREAD

**Issue by r1ghtwr0ng** [martinteoharov/COM2022#1]
I looked around for the RFC specs for the protocol but was unable to find it anywhere. I'm using this in production so can you please update the repo to include this?

**Comment by martinteoharov** [comment]
I think NASA are also using it in prod for their Mars mission, but they havent complained. Grow some balls and make up your own RFC

**Comment by r1ghtwr0ng** [comment]
Fair point











Don't forget that I'm in your walls

**Comment by martinteoharov** [comment]
Im in your head
